wandb_version: 1

alg:
  value: ne_mot
batch_size:
  value: 32
cost:
  value: coulomb
data_dist:
  value: uniform
dim:
  value: 1
epochs:
  value: 25
eps:
  value: 0.1
experiment:
  value: runtime_comparison_coulomb_uniform
k:
  value: 3
lr:
  value: 0.0001
n:
  value: 1000
run:
  value: runtime_sweep
seed:
  value: 3
using_wandb:
  value: 1
wandb_project_name:
  value: NMOT_Runtime_Comparison
